pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/YOURNAME/student_mgmt'
            }
        }

        stage('Install') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Tests') {
            steps {
                sh 'pytest'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t django-students .'
            }
        }
    }
}
